import { createI18n } from 'vue-i18n'
import { appConfig } from '@/config/app'

const messages = {
  'zh-CN': {
    navigation: { workspace: '工作区', showcase: '展示', manage: '管理', resources: '资源', home: '概览', projects: '项目', deployments: '部署', settings: '设置', components: '组件展示', charts: 'ECharts 图表', icons: '图标', table: '数据表格', vueDocs: 'Vue 文档', exampleFrame: '嵌入示例', external: '外部页面' },
    shell: { controls: '全局控制', search: '搜索', searchPlaceholder: '搜索页面和快捷操作…', noResults: '没有匹配的页面', commandHint: '使用上下方向键选择，按 Enter 跳转', notifications: '通知', account: '账户', collapse: '切换导航', theme: '切换主题', language: '切换语言', closeNavigation: '关闭导航', navigation: '主导航', tabs: '页面标签', closeTab: '关闭标签页', closeCurrent: '关闭当前标签页', closeLeft: '关闭左侧标签页', closeRight: '关闭右侧标签页', closeOthers: '关闭其他标签页', closeAll: '关闭全部标签页', reload: '重新加载', team: '团队', allSystemsOperational: '所有系统正常', footerStatus: '由 Fluffy Design Pro 驱动' },
    common: { healthy: '运行正常', review: '待审核', ready: '已就绪', building: '构建中', failed: '失败', close: '关闭' },
    home: { eyebrow: '工作区概览', title: '早上好，Fluffy', description: '这里汇总了项目、部署和团队活动的最新状态。', action: '打开项目', metrics: '关键指标', projects: '活跃项目', deployments: '本周部署', teamMembers: '团队成员', sinceLastWeek: '较上周', recentActivity: '最近活动', activityDescription: '工作区中的最新变更', viewAll: '查看全部', deploymentCompleted: '生产环境部署已完成', projectCreated: '创建了新的项目', memberJoined: '新的团队成员已加入', production: '生产环境', platformStatus: '平台状态', statusDescription: '核心服务运行正常', healthy: '运行正常', edgeNetwork: '边缘网络', buildPipeline: '构建流水线', activityStream: '活动流', operational: '正常', quickActions: '快速开始', quickActionsDescription: '常用工作区操作', newProject: '创建项目', newProjectDescription: '从模板开始新的服务', inviteMember: '邀请成员', inviteMemberDescription: '将协作者添加到团队', reviewDeployments: '查看部署', reviewDeploymentsDescription: '检查最近的生产发布' },
    projects: { eyebrow: '项目空间', title: '项目', description: '在一个位置查看团队所有服务的运行状态。', newProject: '创建项目', active: '活跃项目', activeDescription: '具有最近活动和部署记录的服务。', items: '个项目' },
    deployments: { eyebrow: '发布记录', title: '部署', description: '追踪生产和预览环境中的最近发布。', deploy: '创建部署', deployment: '部署', environment: '环境', status: '状态', duration: '耗时', updated: '更新时间' },
    settings: { eyebrow: '工作区配置', title: '设置', description: '管理团队偏好和通知方式。', workspaceName: '工作区名称', notifications: '部署通知', notificationsDescription: '在生产部署完成后通知团队。', save: '保存更改', saved: '更改已保存' },
    showcase: { eyebrow: '设计系统展示', componentsTitle: '组件', componentsDescription: '用于控制台界面的基础交互状态和表面层级。', actions: '操作', primary: '主操作', secondary: '次操作', dialog: '打开对话框', states: '状态', empty: '空状态', emptyDescription: '这里还没有可显示的内容。', dialogTitle: '准备好继续了吗？', dialogDescription: '这是一个用于展示层级、操作和焦点状态的本地对话框。', chartsTitle: 'ECharts 图表', chartsDescription: '按需注册的响应式图表示例。', traffic: '平台流量', trafficDescription: '请求量与部署频次趋势。', lastSevenDays: '最近 7 天', iconsTitle: '图标', iconsDescription: '与文字权重匹配的当前颜色 SVG 图标。', tableTitle: '数据表格', tableDescription: '带本地过滤和排序能力的紧凑数据表。', filter: '筛选项目…', noResults: '没有匹配的记录' },
    table: { name: '名称', owner: '负责人', status: '状态', updated: '更新时间' },
    external: { eyebrow: '外部资源', description: '该页面在受限 iframe 容器中渲染；若被站点策略阻止，请在新窗口打开。', openNewTab: '在新窗口打开', unavailable: '该外部资源不可用' },
    notFound: { eyebrow: '404', title: '此页面不存在', description: '链接可能已过期，或资源已经被移动。', action: '返回概览' }
  },
  'en-US': {
    navigation: { workspace: 'Workspace', showcase: 'Showcase', manage: 'Manage', resources: 'Resources', home: 'Overview', projects: 'Projects', deployments: 'Deployments', settings: 'Settings', components: 'Components', charts: 'ECharts', icons: 'Icons', table: 'Data table', vueDocs: 'Vue documentation', exampleFrame: 'Embedded example', external: 'External page' },
    shell: { controls: 'Global controls', search: 'Search', searchPlaceholder: 'Search pages and quick actions…', noResults: 'No matching pages', commandHint: 'Use arrow keys to select and Enter to navigate', notifications: 'Notifications', account: 'Account', collapse: 'Toggle navigation', theme: 'Toggle theme', language: 'Switch language', closeNavigation: 'Close navigation', navigation: 'Main navigation', tabs: 'Page tabs', closeTab: 'Close tab', closeCurrent: 'Close current tab', closeLeft: 'Close tabs to the left', closeRight: 'Close tabs to the right', closeOthers: 'Close other tabs', closeAll: 'Close all tabs', reload: 'Reload', team: 'Team', allSystemsOperational: 'All systems operational', footerStatus: 'Powered by Fluffy Design Pro' },
    common: { healthy: 'Healthy', review: 'In review', ready: 'Ready', building: 'Building', failed: 'Failed', close: 'Close' },
    home: { eyebrow: 'Workspace overview', title: 'Good morning, Fluffy', description: 'A concise view of your projects, deployments, and team activity.', action: 'Open projects', metrics: 'Key metrics', projects: 'Active projects', deployments: 'Deployments this week', teamMembers: 'Team members', sinceLastWeek: 'from last week', recentActivity: 'Recent activity', activityDescription: 'The latest changes across your workspace', viewAll: 'View all', deploymentCompleted: 'Production deployment completed', projectCreated: 'Created a new project', memberJoined: 'A new teammate joined', production: 'Production', platformStatus: 'Platform status', statusDescription: 'Core services are running normally', healthy: 'Healthy', edgeNetwork: 'Edge network', buildPipeline: 'Build pipeline', activityStream: 'Activity stream', operational: 'Operational', quickActions: 'Quick actions', quickActionsDescription: 'Common workspace tasks', newProject: 'Create a project', newProjectDescription: 'Start a new service from a template', inviteMember: 'Invite a member', inviteMemberDescription: 'Add a collaborator to your team', reviewDeployments: 'Review deployments', reviewDeploymentsDescription: 'Inspect recent production releases' },
    projects: { eyebrow: 'Project space', title: 'Projects', description: 'See the health of every service your team operates.', newProject: 'New project', active: 'Active projects', activeDescription: 'Services with recent activity and deployments.', items: 'projects' },
    deployments: { eyebrow: 'Release history', title: 'Deployments', description: 'Track recent releases across production and preview environments.', deploy: 'Create deployment', deployment: 'Deployment', environment: 'Environment', status: 'Status', duration: 'Duration', updated: 'Updated' },
    settings: { eyebrow: 'Workspace configuration', title: 'Settings', description: 'Manage team preferences and notification delivery.', workspaceName: 'Workspace name', notifications: 'Deployment notifications', notificationsDescription: 'Notify the team when production deployments complete.', save: 'Save changes', saved: 'Changes saved' },
    showcase: { eyebrow: 'Design system showcase', componentsTitle: 'Components', componentsDescription: 'Core interaction states and surface hierarchy for console interfaces.', actions: 'Actions', primary: 'Primary action', secondary: 'Secondary action', dialog: 'Open dialog', states: 'States', empty: 'Empty state', emptyDescription: 'There is nothing to show here yet.', dialogTitle: 'Ready to continue?', dialogDescription: 'A local dialog for demonstrating hierarchy, actions, and focus states.', chartsTitle: 'ECharts', chartsDescription: 'A responsive chart example with on-demand registration.', traffic: 'Platform traffic', trafficDescription: 'Request and deployment trends.', lastSevenDays: 'Last 7 days', iconsTitle: 'Icons', iconsDescription: 'Current-color SVG icons that match nearby text weight.', tableTitle: 'Data table', tableDescription: 'A compact data table with local filtering and sorting.', filter: 'Filter projects…', noResults: 'No matching records' },
    table: { name: 'Name', owner: 'Owner', status: 'Status', updated: 'Updated' },
    external: { eyebrow: 'External resource', description: 'This page renders in a restricted iframe. Open it in a new tab if the site blocks embedding.', openNewTab: 'Open in new tab', unavailable: 'This external resource is unavailable' },
    notFound: { eyebrow: '404', title: 'This page does not exist', description: 'The link may be outdated or the resource has moved.', action: 'Back to overview' }
  }
}

export const i18n = createI18n({ legacy: false, locale: appConfig.defaultLocale, fallbackLocale: 'en-US', messages })
