import './style.css'

export { Button } from './components/ui/button'
export { Input } from './components/ui/input'
export { Textarea } from './components/ui/textarea'
export { Checkbox } from './components/ui/checkbox'
export { Card } from './components/ui/card'
export { Skeleton } from './components/ui/skeleton'
export { default as FEmpty } from './components/extensions/FEmpty.vue'
export { default as FIcon } from './components/extensions/FIcon.vue'
export { builtinIconNames, iconAliases, registerIcons, resolveIcon } from './lib/icons'
export type { FluffyIconAlias } from './lib/icons'
export { cn } from './lib/utils'
