<script setup lang="ts">
import { computed, shallowRef } from 'vue'
const query = shallowRef('')
const descending = shallowRef(false)
interface TableRow { name: string; owner: string; status: string; updated: string }
const rows: TableRow[] = [{ name: 'console-web', owner: 'Fluffy', status: 'Ready', updated: '4m' }, { name: 'edge-api', owner: 'Mina', status: 'Building', updated: '18m' }, { name: 'design-system', owner: 'Leo', status: 'Review', updated: '1d' }, { name: 'docs-portal', owner: 'Aya', status: 'Ready', updated: '2d' }]
const visibleRows = computed(() => [...rows.filter((row) => row.name.includes(query.value.toLowerCase()))].sort((a, b) => descending.value ? b.name.localeCompare(a.name) : a.name.localeCompare(b.name)))
</script>
<template><section class="page"><header><div><p class="eyebrow">{{ $t('showcase.eyebrow') }}</p><h1>{{ $t('showcase.tableTitle') }}</h1><p>{{ $t('showcase.tableDescription') }}</p></div><input v-model="query" :placeholder="$t('showcase.filter')" /></header><article class="panel"><div class="table"><div class="table-row table-heading"><button type="button" @click="descending=!descending">{{ $t('table.name') }} ↕</button><span>{{ $t('table.owner') }}</span><span>{{ $t('table.status') }}</span><span>{{ $t('table.updated') }}</span></div><div v-for="row in visibleRows" :key="row.name" class="table-row"><strong>{{ row.name }}</strong><span>{{ row.owner }}</span><span class="status" :class="row.status.toLowerCase()">{{ row.status }}</span><time>{{ row.updated }}</time></div><p v-if="!visibleRows.length" class="empty">{{ $t('showcase.noResults') }}</p></div></article></section></template>
<style scoped>
.page{display:grid;gap:24px}.page>header{align-items:flex-end;display:flex;gap:18px;justify-content:space-between}.eyebrow{color:var(--primary);font-size:11px;font-weight:750;letter-spacing:.08em;margin:0 0 10px;text-transform:uppercase}h1{font-size:clamp(1.8rem,3vw,2.5rem);letter-spacing:-.045em;margin:0}header p:not(.eyebrow){color:var(--muted-foreground);font-size:14px;margin:10px 0 0}input{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius-sm);color:var(--foreground);font-size:13px;padding:10px 12px}.panel{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius-lg);box-shadow:var(--shadow-sm);overflow:hidden}.table-row{align-items:center;border-top:1px solid var(--border);display:grid;gap:14px;grid-template-columns:1.4fr 1fr .8fr .4fr;padding:14px 18px}.table-heading{border:0;color:var(--subtle-foreground);font-size:10px;font-weight:700;letter-spacing:.06em;text-transform:uppercase}.table-heading button{background:transparent;border:0;color:inherit;cursor:pointer;font:inherit;padding:0;text-align:start}.table-row strong{font-size:13px}.table-row span,.table-row time{color:var(--muted-foreground);font-size:12px}.status{font-weight:700}.status.ready{color:var(--success)}.status.building{color:var(--warning)}.status.review{color:var(--primary)}.empty{color:var(--muted-foreground);font-size:13px;padding:28px;text-align:center}@media(max-width:620px){.page>header{align-items:stretch;flex-direction:column}.table-row{grid-template-columns:1fr auto}.table-row :nth-child(2),.table-row :nth-child(4),.table-heading{display:none}}
</style>