export const uiCatalog = [
  { source: 'src/components/ui/button/Button.vue', target: 'src/components/ui/button/Button.vue', group: 'button' },
  { source: 'src/components/ui/button/index.ts', target: 'src/components/ui/button/index.ts', group: 'button' },
  { source: 'src/components/ui/input/Input.vue', target: 'src/components/ui/input/Input.vue', group: 'input' },
  { source: 'src/components/ui/input/index.ts', target: 'src/components/ui/input/index.ts', group: 'input' },
  { source: 'src/components/ui/textarea/Textarea.vue', target: 'src/components/ui/textarea/Textarea.vue', group: 'textarea' },
  { source: 'src/components/ui/textarea/index.ts', target: 'src/components/ui/textarea/index.ts', group: 'textarea' },
  { source: 'src/components/ui/checkbox/Checkbox.vue', target: 'src/components/ui/checkbox/Checkbox.vue', group: 'checkbox' },
  { source: 'src/components/ui/checkbox/index.ts', target: 'src/components/ui/checkbox/index.ts', group: 'checkbox' },
  { source: 'src/components/ui/card/Card.vue', target: 'src/components/ui/card/Card.vue', group: 'card' },
  { source: 'src/components/ui/card/index.ts', target: 'src/components/ui/card/index.ts', group: 'card' },
  { source: 'src/components/ui/skeleton/Skeleton.vue', target: 'src/components/ui/skeleton/Skeleton.vue', group: 'skeleton' },
  { source: 'src/components/ui/skeleton/index.ts', target: 'src/components/ui/skeleton/index.ts', group: 'skeleton' },
  { source: 'src/components/extensions/FEmpty.vue', target: 'src/components/extensions/FEmpty.vue', group: 'empty' },
  { source: 'src/components/extensions/FEmpty.test.ts', target: 'src/components/extensions/FEmpty.test.ts', group: 'empty' },
  { source: 'src/components/extensions/FIcon.vue', target: 'src/components/extensions/FIcon.vue', group: 'icon' },
  { source: 'src/components/extensions/FIcon.test.ts', target: 'src/components/extensions/FIcon.test.ts', group: 'icon' },
  { source: 'src/lib/icons.ts', target: 'src/lib/icons.ts', group: 'icon' },
  { source: 'src/lib/utils.ts', target: 'src/lib/utils.ts', group: 'utils' },
  { source: 'src/styles/tokens.css', target: 'src/styles/tokens.css', group: 'style' },
]
